# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 21:50
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicearea',
            name='company',
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to='service_api.Company'),
            preserve_default=False,
        ),
    ]
