# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_api', '0003_servicetype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
